### ISSUE TITLE
Problem on starting frontend

### ISSUE THREAD

**Issue by teoalpuy19** [chrisleekr/yii2-angular2-boilerplate#1]
When I run the npm start. Shows me this. I don't know how to fix it!
Thanks!
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/mateoalpuy/yii2-angular2-boilerplate/frontend/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mateoalpuy/yii2-angular2-boilerplate/frontend/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by teoalpuy19** [comment]
I fix it!

**Comment by chrisleekr** [comment]
Hi @teoalpuy19 

Good to hear you fixed it. :)
